### PR TITLE
Detect missing processes

### LINKED ISSUE #1643: yb-ctl destroy hits OSError: [Errno 3] No such process if cluster doesn't
In some cases, `yb-ctl destroy` seems to hit this error.

Steps to repro:

1. This step is expected to fail because we artifically force the same IP/port for all three yb-tserver processes on the node. So only 1 of them will start, and the others will fail.
```
$ ./bin/yb-ctl --rf 3 start --tserver_flags="redis_proxy_bind_address=0.0.0.0:6123"
Creating cluster.
Waiting for cluster to be ready.
----------------------------------------------------------------------------------------------------
| Node Count: 3 | Replication Factor: 3                                                            |
----------------------------------------------------------------------------------------------------
| JDBC                : postgresql://postgres@127.0.0.1:5433                                       |
| YSQL Shell          : ./bin/ysqlsh                                                               |
| YCQL Shell          : ./bin/cqlsh                                                                |
| YEDIS Shell         : ./bin/redis-cli -h 127.0.0.1 -p 6379                                       |
| Web UI              : http://127.0.0.1:7000/                                                     |
| Cluster Data        : /home/centos/yugabyte-data                                                 |
----------------------------------------------------------------------------------------------------
```

2. Confirm that two of the yb-tserver processes didn't start:
```
$ ./bin/yb-ctl status | grep yb-
./bin/yb-ctl status | grep yb-
| Node 1: yb-tserver (pid 22222), yb-master (pid 22213)                                            |
| data-dir[0]         : /home/centos/yugabyte-data/node-1/disk-1/yb-data                           |
| yb-tserver Logs     : /home/centos/yugabyte-data/node-1/disk-1/yb-data/tserver/logs              |
| yb-master Logs      : /home/centos/yugabyte-data/node-1/disk-1/yb-data/master/logs               |
| Node 2: yb-tserver (Stopped), yb-master (pid 22216)                                              |
| data-dir[0]         : /home/centos/yugabyte-data/node-2/disk-1/yb-data                           |
| yb-tserver Logs     : /home/centos/yugabyte-data/node-2/disk-1/yb-data/tserver/logs              |
| yb-master Logs      : /home/centos/yugabyte-data/node-2/disk-1/yb-data/master/logs               |
| Node 3: yb-tserver (Stopped), yb-master (pid 22219)                                              |
| data-dir[0]         : /home/centos/yugabyte-data/node-3/disk-1/yb-data                           |
| yb-tserver Logs     : /home/centos/yugabyte-data/node-3/disk-1/yb-data/tserver/logs              |
| yb-master Logs      : /home/centos/yugabyte-data/node-3/disk-1/yb-data/master/logs               |
```

3. Now, an attempt to yb-ctl destroy hits this issue:
```
$ ./bin/yb-ctl destroy
./bin/yb-ctl destroy
Destroying cluster.
Traceback (most recent call last):
  File "./bin/yb-ctl", line 1658, in <module>
    control.run()
  File "./bin/yb-ctl", line 1631, in run
    self.args.func()
  File "./bin/yb-ctl", line 1463, in destroy_cmd_impl
    self.for_all_daemons(self.stop_daemon)
  File "./bin/yb-ctl", line 1398, in for_all_daemons
    fn(DaemonId(daemon_type, daemon_index))
  File "./bin/yb-ctl", line 1172, in stop_daemon
    self.stop_process(postgres_pid, "Postmaster for {}".format(daemon_id))
  File "./bin/yb-ctl", line 1142, in stop_process
    os.kill(pid, signal.SIGTERM)
OSError: [Errno 3] No such process
2019-06-27 21:53:39,372 INFO: Stopping Server master-1 PID=22213
2019-06-27 21:53:39,373 INFO: Waiting for Server master-1 PID=22213 to stop...
2019-06-27 21:53:39,886 INFO: Stopping Server master-2 PID=22216
2019-06-27 21:53:39,886 INFO: Waiting for Server master-2 PID=22216 to stop...
2019-06-27 21:53:40,399 INFO: Stopping Server master-3 PID=22219
2019-06-27 21:53:40,399 INFO: Waiting for Server master-3 PID=22219 to stop...
2019-06-27 21:53:40,912 INFO: Stopping Server tserver-1 PID=22222
2019-06-27 21:53:40,912 INFO: Waiting for Server tserver-1 PID=22222 to stop...
2019-06-27 21:53:41,424 INFO: Server tserver-2 already stopped
2019-06-27 21:53:41,424 INFO: Stopping Postmaster for tserver-2 PID=22347
^^^ Encountered errors ^^^
```

### PR DESCRIPTION
**Pull request by jaki**
Resolves YugaByte/yugabyte-db#1643 and YugaByte/yugabyte-db#1729.

For `yb-ctl`, add various process existence checks:
* Ensure that no master or tserver processes exist at the beginning of
  performing a `create`: added in `ClusterControl.pre_create_checks`
* Ensure that master and tserver processes exist after
  `ClusterControl.start_daemon`s when performing a `create` or `start`:
  addressed by `call_check_for_processes` in
  `ClusterControl.wait_for_cluster`
* Ensure that master and tserver processes continue to exist while
  performing calls to yb-admin in `ClusterControl.wait_for_cluster`:
  addressed by `call_check_for_processes` in `call_check_for_ts`
* Allow PIDs referenced by `postmaster.pid` to refer to already dead
  postgres processes: added in `ClusterControl.stop_process`

### CODE REVIEW

**Comment by rkarthik007** [comment]
@WesleyW - would be good to take a look at the fixes here and see if we need to incorporate any in `yugabyte-db`. cc @bmatican @schoudhury

**Comment by mbautin** [comment]
@jj-kim please take a look at the test failures at https://travis-ci.org/YugaByte/yugabyte-installation/jobs/556584742

File: .gitignore [hunk 1]
```diff
@@ -4,3 +4,5 @@
 *.sw?
 *.bak
 *.rej
+venv/
```
Comment (bmatican) [inline .gitignore:7]: why is there a `venv` here?

File: bin/yb-ctl [hunk 2]
```diff
@@ -1246,8 +1246,14 @@ class ClusterControl:
             logging.info("{} already stopped".format(name))
             return
         logging.info("Stopping {} PID={}".format(name, pid))
-        # Kill the process.
-        os.kill(pid, signal.SIGTERM)
+        # Kill the process, if it exists.
+        try:
+            os.kill(pid, signal.SIGTERM)
+        except OSError as e:
+            if e.errno == 3:
```
Comment (bmatican) [inline bin/yb-ctl]: is there some os.CONSTANT we can use instead of just 3 :)

File: bin/yb-ctl [hunk 3]
```diff
@@ -1297,7 +1303,10 @@ class ClusterControl:
         self.stop_daemon(daemon_id)
         self.start_daemon(daemon_id)
 
-    def start_helper(self, server_counts_map):
+    def create_ready_check(self):
```
Comment (bmatican) [inline bin/yb-ctl]: nit: maybe call it `pre_create_checks`

File: bin/yb-ctl [hunk 4]
```diff
@@ -1520,18 +1549,19 @@ class ClusterControl:
...
 
-    def for_all_daemons(self, fn, server_counts_map=None):
+    def for_all_daemons(self, fn):
         """
         Run the given function for all daemons.
+
+        :returns: return values of each function call.
+        :rtype: dict
         """
+        fn_returns = {daemon_type: [] for daemon_type in DAEMON_TYPES}
```
Comment (bmatican) [inline bin/yb-ctl]: nit: I normally use dict.setdefault(key, []) so I don't have to preinitialize

File: test/yb-ctl-test.sh [hunk 5]
```diff
@@ -227,6 +235,15 @@ log "OSTYPE: $OSTYPE"
 log "USER: $USER"
 log "TRAVIS: ${TRAVIS:-undefined}"
 
+if [[ ${TRAVIS:-} == "true" && $OSTYPE == darwin* ]]; then
```
Comment (bmatican) [inline test/yb-ctl-test.sh:240]: nit: add a comment that mac needs loopback aliases explicitly created

File: bin/yb-ctl [hunk 6]
```diff
@@ -1342,6 +1355,18 @@ class ClusterControl:
...
         """
+        # Wait for master and tserver processes to be ready.
+        def call_check_for_processes(should_get_error):
+            pids = self.for_all_daemons(self.get_pid)
+            if self.args.verbose:
+                logging.info("Daemon PIDs found after starting daemons: {}".format(pids))
+            return all(sum(pids.values(), []))
+
+        logging.info("Waiting for master and tserver processes to be up.")
+        if not retry_call_with_timeout(call_check_for_processes, self.options.timeout):
```
Comment (bmatican) [inline bin/yb-ctl]: instead of the overall timeout here, I'd add a new constant at the top, maybe like 5 seconds, since really, if the processes do not come up in a couple of seconds, they likely crashed

File: bin/yb-ctl [hunk 7]
```diff
@@ -1342,6 +1355,18 @@ class ClusterControl:
         alive (based on valid PID), then this function returns True. Anything else will end up
         returning False.
         """
+        # Wait for master and tserver processes to be ready.
+        def call_check_for_processes(should_get_error):
+            pids = self.for_all_daemons(self.get_pid)
+            if self.args.verbose:
+                logging.info("Daemon PIDs found after starting daemons: {}".format(pids))
+            return all(sum(pids.values(), []))
```
Comment (bmatican) [inline bin/yb-ctl:1414]: why do we need a sum here? isn't pids already a list, with some items being None? won't all(pids) be enough?

File: bin/yb-ctl [hunk 8]
```diff
@@ -1357,6 +1382,9 @@ class ClusterControl:
         num_yb_admin_ts = None
 
         def call_check_for_ts(should_get_error):
+            if not call_check_for_processes(should_get_error):
+                raise ExitWithError("At least one master or tserver process is down.")
```
Comment (bmatican) [inline bin/yb-ctl:1440]: I think we should also have one more debug function where, if we know some processes are down, we log out the respective yb-master.err / yb-tserver.err file for said process, in the hopes of highlighting why it crashed. We can then use that function both here and in line 1367, since at the end of that loop, we know we should be failing as well

File: bin/yb-ctl [hunk 9]
```diff
@@ -1520,18 +1549,19 @@ class ClusterControl:
...
+        :rtype: dict
         """
+        fn_returns = {daemon_type: [] for daemon_type in DAEMON_TYPES}
         for daemon_type in DAEMON_TYPES:
-            if server_counts_map:
-                num_servers = server_counts_map[daemon_type]
-            else:
-                num_servers = self.get_number_of_servers(daemon_type)
-
+            num_servers = self.get_number_of_servers(daemon_type)
```
Comment (bmatican) [inline bin/yb-ctl:1615]: wait, how does this work during `create`?? we won't have the respective directories created per node, for `get_number_of_servers` to actually be able to return the correct numbers...

**Review by bmatican — CHANGES_REQUESTED** [review]

File: .gitignore (hunk 1 above)
Comment (jaki) [reply .gitignore:7]: That was @mbautin, commit 963b3d8.  I was using a virtual environment.

File: bin/yb-ctl (hunk 6 above)
Comment (jaki) [reply bin/yb-ctl]: Forgot to mention that I didn't work on this.  So this timeout is hard-coded and not exposed to the user?

File: bin/yb-ctl (hunk 7 above)
Comment (jaki) [reply bin/yb-ctl:1414]: `pids` is a dict with two keys and list values.  The `sum` flattens it.

File: bin/yb-ctl (hunk 9 above)
Comment (jaki) [reply bin/yb-ctl:1615]: It goes into the first if case, which uses replication factor.

File: bin/yb-ctl (hunk 7 above)
Comment (jaki) [reply bin/yb-ctl:1414]: The signature for `for_all_daemons` could change to just return a flattened list, but that would be a loss of information.  One consequence is that the log message above would be less clear.

File: bin/yb-ctl [hunk 10]
```diff
@@ -1335,13 +1348,43 @@ class ClusterControl:
         if not retry_call_with_timeout(call_change_config, self.options.timeout):
             raise ExitWithError("Could not change master config...")
 
+    def dump_missing_process_error_logs(self):
+        pids = self.for_all_daemons(self.get_pid)
+        for daemon_type, pid_list in pids.items():
```
Comment (bmatican) [inline bin/yb-ctl]: nit: prefer iteritems over items

File: bin/yb-ctl [hunk 11]
```diff
@@ -1335,13 +1348,43 @@ class ClusterControl:
...
+            for index, pid in enumerate(pid_list, 1):
```
Comment (bmatican) [inline bin/yb-ctl:1394]: why do we start at 1?

File: bin/yb-ctl [hunk 12]
```diff
@@ -1335,13 +1348,43 @@ class ClusterControl:
...
+                if pid is None:
+                    daemon_id = DaemonId(daemon_type, index)
+                    node_base_dirs = self.get_base_node_dirs(daemon_id.index)
+                    first_base_dir = node_base_dirs[0]
+                    log_name = daemon_id.daemon_type + ".err"
+                    log_path = os.path.join(first_base_dir, log_name)
```
Comment (bmatican) [inline bin/yb-ctl]: we should already be constructing this path when we start the daemon, can we just make this be a function to pick up the .err / .out path?

File: bin/yb-ctl [hunk 13]
```diff
@@ -1335,13 +1348,43 @@ class ClusterControl:
...
+                    if os.path.exists(log_path):
```
Comment (bmatican) [inline bin/yb-ctl:1398]: maybe for missing .err file, we should also log something like `process failed without writing out any error logs..`

File: bin/yb-ctl [hunk 14]
```diff
@@ -1335,13 +1348,43 @@ class ClusterControl:
...
+                        with open(log_path) as log:
+                            print("Viewing log at {}:".format(log_path), file=sys.stderr)
+                            if sys.version_info[0] >= 3:
```
Comment (bmatican) [inline bin/yb-ctl]: we also have a spot where we dump the log to stderr if we have errors, can we make a shared function for both of these

File: bin/yb-ctl (hunk 7 above)
Comment (bmatican) [reply bin/yb-ctl:1414]: ah makes sense, my bad, didn't realize the signature

File: bin/yb-ctl [hunk 15]
```diff
@@ -1335,13 +1348,43 @@ class ClusterControl:
...
         returning False.
         """
+        # Wait for master and tserver processes to be ready.
+        def call_check_for_processes(should_get_error):
+            pids = self.for_all_daemons(self.get_pid)
+            logging.info("PIDs found: {}".format(pids))
+            return all(sum(pids.values(), []))
+
+        logging.info("Waiting for master and tserver processes to be up.")
+        if not retry_call_with_timeout(call_check_for_processes, MAX_PROCESS_WAIT_SECONDS):
```
Comment (bmatican) [inline bin/yb-ctl]: @mbautin you ok with this particular wait for processes to come up to not be tied to the overall `--timeout` option? This is how much time to wait for the cluster processes to all be up, which we'd expect to happen pretty fast or not at all...

I think we default that to 45s, probably due to previous `initdb` slowdown. I had suggested to @jj-kim to make this a separate constant with lower value (5-10s).

File: bin/yb-ctl [hunk 16]
```diff
@@ -1335,13 +1348,43 @@ class ClusterControl:
...
         """
         This will wait for the masters to elect a leader and then keep querying for how many TS
         the master is aware of. When that number reaches the number of TS that yb-ctl believes are
         alive (based on valid PID), then this function returns True. Anything else will end up
         returning False.
         """
+        # Wait for master and tserver processes to be ready.
+        def call_check_for_processes(should_get_error):
+            pids = self.for_all_daemons(self.get_pid)
+            logging.info("PIDs found: {}".format(pids))
```
Comment (bmatican) [inline bin/yb-ctl]: nit: this will be logged all per check, which might be spammy...why not just log it in the error checking if outside? or even better, just in `dump_missing_process_error_logs`?

File: bin/yb-ctl (hunk 9 above)
Comment (bmatican) [reply bin/yb-ctl:1615]: oooh, because of `        self.creating_cluster = True`!

**Review by bmatican — CHANGES_REQUESTED** [review]
Mostly minor stuff, should be good to go after this, I think.

File: bin/yb-ctl (hunk 11 above)
Comment (jaki) [reply bin/yb-ctl:1394]: Daemon indices start at 1.

File: bin/yb-ctl [hunk 17]
```diff
@@ -1348,23 +1365,33 @@ class ClusterControl:
         if not retry_call_with_timeout(call_change_config, self.options.timeout):
             raise ExitWithError("Could not change master config...")
 
+    def keep_and_dump_log(self, log_path):
```
Comment (bmatican) [inline bin/yb-ctl]: nit: can we rename this to just `dump_file_to_stderr`, since having a `keep_` prefix makes me think we would also have an API that removes it.

**Review by bmatican — APPROVED** [review]
Let's check with @mbautin real quick offline, if he thinks this new timeout being shorter and not CLI changeable is fine with him to.

File: bin/yb-ctl [hunk 18]
```diff
@@ -540,7 +541,8 @@ class ClusterOptions:
     def __init__(self):
         self.max_daemon_index = 20
         self.num_shards_per_tserver = None
-        self.timeout = None
+        self.timeout_yb_admin = None
```
Comment (mbautin) [inline bin/yb-ctl]: `timeout_yb_admin_sec`

File: bin/yb-ctl [hunk 19]
```diff
@@ -106,7 +106,8 @@ YEDIS_DEFAULT_PORT = 6379
 LOCALHOST_IP = '127.0.0.1'
 
 SLEEP_TIME_IN_SEC = 1
-MAX_WAIT_SECONDS = 45
+MAX_YB_ADMIN_WAIT_SECONDS = 45
+MAX_CLUSTER_UP_WAIT_SECONDS = 10
```
Comment (mbautin) [inline bin/yb-ctl]: Instead of "cluster up", this should say "processes running", because that's what we are testing.
E.g. MAX_WAIT_FOR_PROCESSES_RUNNING_SEC

File: bin/yb-ctl [hunk 20]
```diff
@@ -540,7 +541,8 @@ class ClusterOptions:
     def __init__(self):
         self.max_daemon_index = 20
         self.num_shards_per_tserver = None
-        self.timeout = None
+        self.timeout_yb_admin = None
+        self.timeout_cluster_up = None
```
Comment (mbautin) [inline bin/yb-ctl]: `timeout_processes_running_sec`

File: bin/yb-ctl [hunk 21]
```diff
@@ -906,8 +927,11 @@ class ClusterControl:
             "--num_shards_per_tserver", default=2, type=int,
             help="Number of shards (tablets) to start per tablet server for each table.")
         self.parser.add_argument(
-            "--timeout", default=MAX_WAIT_SECONDS, type=float,
-            help="Timeout in seconds for operations that wait on the cluster")
+            "--timeout-yb-admin", default=MAX_YB_ADMIN_WAIT_SECONDS, type=float,
+            help="Timeout in seconds for operations that call yb-admin and wait on the cluster")
+        self.parser.add_argument(
+            "--timeout-cluster-up", default=MAX_CLUSTER_UP_WAIT_SECONDS, type=float,
```
Comment (mbautin) [inline bin/yb-ctl]: timeout-processes-running-sec

File: bin/yb-ctl [hunk 22]
```diff
@@ -906,8 +927,11 @@ class ClusterControl:
             "--num_shards_per_tserver", default=2, type=int,
             help="Number of shards (tablets) to start per tablet server for each table.")
         self.parser.add_argument(
-            "--timeout", default=MAX_WAIT_SECONDS, type=float,
-            help="Timeout in seconds for operations that wait on the cluster")
+            "--timeout-yb-admin", default=MAX_YB_ADMIN_WAIT_SECONDS, type=float,
```
Comment (mbautin) [inline bin/yb-ctl]: timeout-yb-admin-sec

**Review by mbautin — APPROVED** [review]
